//! Code Generation
//!
//! Generates code content based on patterns and conventions.

use crate::analyzer::{AnalyzedContext, DetectedPattern};
use crate::types::Language;

/// Code generator
pub struct CodeGenerator {
    /// Generated templates
    templates: Vec<Template>,
}

impl CodeGenerator {
    /// Create new generator
    pub fn new() -> Self {
        Self {
            templates: Vec::new(),
        }
    }

    /// Generate code following patterns
    pub fn generate(
        &self,
        spec: &GenerationSpec,
        context: &AnalyzedContext,
    ) -> String {
        // TODO: Implement actual code generation
        // For now, return placeholder based on language
        match spec.language {
            Language::Rust => self.generate_rust(spec, context),
            Language::TypeScript => self.generate_typescript(spec, context),
            Language::JavaScript => self.generate_javascript(spec, context),
            Language::Python => self.generate_python(spec, context),
            _ => self.generate_generic(spec, context),
        }
    }

    fn generate_rust(&self, spec: &GenerationSpec, _context: &AnalyzedContext) -> String {
        format!(
            r#"//! {}
//!
//! Generated by Dooz-Code

use std::error::Error;

/// TODO: Implement {}
pub fn {}() -> Result<(), Box<dyn Error>> {{
    todo!("Implementation pending")
}}

#[cfg(test)]
mod tests {{
    use super::*;

    #[test]
    fn test_{}() {{
        // TODO: Add tests
    }}
}}
"#,
            spec.description,
            spec.name,
            to_snake_case(&spec.name),
            to_snake_case(&spec.name)
        )
    }

    fn generate_typescript(&self, spec: &GenerationSpec, _context: &AnalyzedContext) -> String {
        format!(
            r#"/**
 * {}
 * Generated by Dooz-Code
 */

export interface {}Props {{
  // TODO: Define props
}}

export function {}(props: {}Props): void {{
  // TODO: Implement
  throw new Error('Not implemented');
}}
"#,
            spec.description,
            spec.name,
            to_camel_case(&spec.name),
            spec.name
        )
    }

    fn generate_javascript(&self, spec: &GenerationSpec, _context: &AnalyzedContext) -> String {
        format!(
            r#"/**
 * {}
 * Generated by Dooz-Code
 */

export function {}() {{
  // TODO: Implement
  throw new Error('Not implemented');
}}
"#,
            spec.description,
            to_camel_case(&spec.name)
        )
    }

    fn generate_python(&self, spec: &GenerationSpec, _context: &AnalyzedContext) -> String {
        format!(
            r#"\"\"\"
{}
Generated by Dooz-Code
\"\"\"

def {}():
    \"\"\"TODO: Implement\"\"\"
    raise NotImplementedError()
"#,
            spec.description,
            to_snake_case(&spec.name)
        )
    }

    fn generate_generic(&self, spec: &GenerationSpec, _context: &AnalyzedContext) -> String {
        format!("// {}\n// Generated by Dooz-Code\n// TODO: Implement\n", spec.description)
    }
}

impl Default for CodeGenerator {
    fn default() -> Self {
        Self::new()
    }
}

/// Generation specification
#[derive(Debug, Clone)]
pub struct GenerationSpec {
    /// Name of thing to generate
    pub name: String,
    
    /// Description
    pub description: String,
    
    /// Target language
    pub language: Language,
    
    /// Generation type
    pub gen_type: GenerationType,
    
    /// Patterns to follow
    pub patterns: Vec<DetectedPattern>,
}

impl GenerationSpec {
    /// Create new spec
    pub fn new(name: impl Into<String>, language: Language) -> Self {
        Self {
            name: name.into(),
            description: String::new(),
            language,
            gen_type: GenerationType::Function,
            patterns: Vec::new(),
        }
    }

    /// With description
    pub fn with_description(mut self, description: impl Into<String>) -> Self {
        self.description = description.into();
        self
    }

    /// With type
    pub fn of_type(mut self, gen_type: GenerationType) -> Self {
        self.gen_type = gen_type;
        self
    }
}

/// Type of generation
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum GenerationType {
    Function,
    Class,
    Module,
    Test,
    Interface,
}

/// Code template
#[derive(Debug, Clone)]
pub struct Template {
    /// Template name
    pub name: String,
    
    /// Target language
    pub language: Language,
    
    /// Template content with placeholders
    pub content: String,
}

/// Convert to snake_case
fn to_snake_case(s: &str) -> String {
    let mut result = String::new();
    for (i, c) in s.chars().enumerate() {
        if c.is_uppercase() && i > 0 {
            result.push('_');
        }
        result.push(c.to_lowercase().next().unwrap_or(c));
    }
    result
}

/// Convert to camelCase
fn to_camel_case(s: &str) -> String {
    let mut result = String::new();
    let mut capitalize_next = false;
    
    for (i, c) in s.chars().enumerate() {
        if c == '_' || c == '-' {
            capitalize_next = true;
            continue;
        }
        
        if capitalize_next {
            result.extend(c.to_uppercase());
            capitalize_next = false;
        } else if i == 0 {
            result.extend(c.to_lowercase());
        } else {
            result.push(c);
        }
    }
    result
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn generate_rust_code() {
        let generator = CodeGenerator::new();
        let spec = GenerationSpec::new("MyFunction", Language::Rust)
            .with_description("Test function");

        let dir = tempfile::tempdir().unwrap();
        let context = crate::types::RepoContext::from_path(dir.path()).unwrap();
        let analyzed = crate::analyzer::RepoAnalyzer::new().analyze(&context).unwrap();

        let code = generator.generate(&spec, &analyzed);
        assert!(code.contains("my_function"));
        assert!(code.contains("Dooz-Code"));
    }

    #[test]
    fn case_conversions() {
        assert_eq!(to_snake_case("MyFunction"), "my_function");
        assert_eq!(to_camel_case("my_function"), "myFunction");
    }
}
